# Generated by Django 3.2.5 on 2021-07-30 16:23

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAccountCredentials",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
                (
                    "aws_access_key",
                    fernet_fields.fields.EncryptedCharField(
                        blank=True, default=None, max_length=255
                    ),
                ),
                (
                    "aws_secret_key",
                    fernet_fields.fields.EncryptedCharField(
                        blank=True, default=None, max_length=255
                    ),
                ),
                (
                    "drbx_access_token",
                    fernet_fields.fields.EncryptedCharField(
                        blank=True, default=None, max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "External account credentials",
            },
        ),
    ]
