# Generated by Django 3.2.11 on 2022-01-10 19:17

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gcc", "0002_auto_20220103_1054"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachinePool",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="auth.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "pem",
                    fernet_fields.fields.EncryptedCharField(
                        blank=True, default=None, max_length=255
                    ),
                ),
                (
                    "pool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gcc.machinepool",
                    ),
                ),
            ],
        ),
    ]
