# Generated by Django 3.2.11 on 2022-01-10 19:47

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcc", "0004_alter_machine_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="ip",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="machine",
            name="pem",
            field=fernet_fields.fields.EncryptedCharField(
                blank=True, default=None, max_length=4096
            ),
        ),
    ]
