# Generated by Django 3.2.11 on 2022-01-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcc", "0008_auto_20220111_1131"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="status",
            field=models.CharField(blank=True, default="Available", max_length=255),
        ),
    ]
