# Generated by Django 3.2.11 on 2022-01-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcc", "0003_machine_machinepool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="ip",
            field=models.CharField(blank=True, default=None, max_length=4096),
        ),
    ]
