# Generated by Django 3.2.11 on 2022-01-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcc", "0005_auto_20220110_1447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machines",
                to="gcc.machinepool",
            ),
        ),
    ]
