# Generated by Django 3.2.11 on 2022-01-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gcc", "0006_alter_machine_pool"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="mac_id",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
