name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python 3.10.2
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.10.2
      - name: Setup poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install dependencies
        run: poetry install
      - name: Run black
        if: always()
        run: poetry run task black
      - name: Run flake8
        if: always()
        run: poetry run task flake8